map:
  cell_size: 0.1 #m
  map_width: 500 #cells
  map_height: 500 #cells
  robot_offset: 0 # offset between robot and the center of the map on the x axis
  rotation: true #rotation of the map
  lambda_max: 1.0e+5 #max value of lambda
  lambda_unmeasured: 0 #value of lambda in unmeasured cells 
sensor:
  error_region_x: 0.2 #m
  error_region_y: 0.2 #m
  ph: 0.99
  pm: 0.9999
topics:
  laserScan: '/scan' 
  occupancyGrid: '/occupancyGrid'
  massGrid: '/massGrid'
  lambdaGrid: '/lambdaGrid'
  publish_rate: 1 #Hz
tf:
  odom: 'odom'
  lidar: 'laser'
  robot: 'base_link'
normals_estimation:
  neighbor_radius: 20 #neighbors
  max_radius: 2.0 #meters
  min_neighbors: 3 #neighbors

